version: "3.9"
services:
  portainer:
    container_name: portainer_dev_a
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volume_dev_a/PORTAINER_DEV_A/portainer-data:/data
    ports:
      - 9000:9000
    networks:
      - net_dev_a

  sqlserver_dev_a:
    container_name: sqlserver_dev_a
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    volumes:
      - ./volume_dev_a/SQLSERVER_DEV_A:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "S3gr3d0#@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      - net_dev_a

  mysql_dev_a:
    container_name: mysql_dev_a
    image: mysql
    ports:
      - "3306:3306"
    command: mysqld --authentication-policy=mysql_native_password --skip-mysqlx --lower_case_table_names=0 --default-time-zone=+00:00
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd#@
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin
      MYSQL_DATABASE: dbgestao
      TZ: UTC
    networks:
      - net_dev_a

  adminer_dev_a:
    container_name: adminer_dev_a
    image: adminer
    depends_on:
      - mysql_dev_a
    ports:
      - 8080:8080
    networks:
      - net_dev_a

  nifi_dev_a:
    container_name: nifi_dev_a
    image: "apache/nifi:latest"
    volumes:
      - ./volume_dev_a/NIFI_DEV_A/database_repository:/opt/nifi/nifi-current/database_repository
      - ./volume_dev_a/NIFI_DEV_A/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./volume_dev_a/NIFI_DEV_A/content_repository:/opt/nifi/nifi-current/content_repository
      - ./volume_dev_a/NIFI_DEV_A/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./volume_dev_a/NIFI_DEV_A/state:/opt/nifi/nifi-current/state
      - ./volume_dev_a/NIFI_DEV_A/logs:/opt/nifi/nifi-current/logs
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvv
    ports:
      - "8443:8443"
    networks:
      - net_dev_a

  rabbitmq_dev_a:
    container_name: 'rabbitmq_dev_a'
    image: rabbitmq:3.9.13-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./volume_dev_a/RABBITMQ_DEV_A/data/:/var/lib/rabbitmq/
      - ./volume_dev_a/RABBITMQ_DEV_A/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net_dev_a

  elasticsearch:
    container_name: elasticsearch_dev_a
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.templates.enabled: "true"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net_dev_a

  kibana:
    container_name: kibana_dev_a
    image: docker.elastic.co/kibana/kibana:8.1.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch_dev_a:9200
    ports:
      - "5601:5601"
    networks:
      - net_dev_a

networks:
  net_dev_a:
    driver: bridge

volumes:
  volume_dev_a:
    driver: local
